# Generated by Django 4.2.6 on 2024-10-27 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_viewersprofilemodel_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('Number_of_opening', models.PositiveIntegerField(null=True)),
                ('category', models.CharField(choices=[('full_time', 'Full_time'), ('part_time', 'Part_time')], max_length=100, null=True)),
                ('Job_descriptons', models.TextField(max_length=200, null=True)),
                ('skill', models.CharField(max_length=200, null=True)),
                ('Image', models.ImageField(null=True, upload_to='Media/Job_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
