# Generated by Django 4.2.6 on 2024-10-27 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='application',
            name='cover',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jobmodel'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ImageField(null=True, upload_to='Media/Resume'),
        ),
    ]
