# Generated by Django 5.0.3 on 2024-10-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recuritersprofilemodel',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='recuritersprofilemodel',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='recuritersprofilemodel',
            name='Profile_Pic',
        ),
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='Profile_Pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to='Media/Profile_Pic'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('hardware', 'Hardware'), ('software', 'Software'), ('data science', 'Data Science'), ('cyber security', 'Cyber Security'), ('digital marketing', 'Digital Marketing'), ('cloud computing', 'Cloud Computing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='skill',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('hardware', 'Hardware'), ('software', 'Software'), ('data science', 'Data Science'), ('cyber security', 'Cyber Security'), ('digital marketing', 'Digital Marketing'), ('cloud computing', 'Cloud Computing')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='BasicInfoModel',
        ),
    ]
