# Generated by Django 5.0.3 on 2024-10-31 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_recuritersprofilemodel_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Display_name',
        ),
    ]
