# Generated by Django 5.0.3 on 2024-10-31 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_jobmodel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='updated_at',
        ),
    ]
