# Generated by Django 5.0.3 on 2024-10-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_jobmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='skills',
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('hardware', 'Hardware'), ('software', 'Software'), ('data science', 'Data Science'), ('cyber security', 'Cyber Security'), ('digital marketing', 'Digital Marketing'), ('cloud computing', 'Cloud Computing')], max_length=100, null=True),
        ),
    ]
