# Generated by Django 5.0.3 on 2024-11-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_seekerprofilemodel_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='skills',
        ),
        migrations.AddField(
            model_name='application',
            name='skill',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('hardware', 'Hardware'), ('software', 'Software'), ('data science', 'Data Science'), ('cyber security', 'Cyber Security'), ('digital marketing', 'Digital Marketing'), ('cloud computing', 'Cloud Computing')], max_length=200, null=True),
        ),
    ]
