# Generated by Django 5.0.3 on 2024-11-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_application_skills_application_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='skill',
            new_name='skills',
        ),
    ]
